I2SMIC_FOLDER ?= updates/snd-i2c_mic

I2SMIC_MODULE:
	make clean -C $(I2SMIC_FOLDER) KDIR=$(KERNEL_OUT)
	make -j4 -C $(I2SMIC_FOLDER) ARCH=arm KDIR=$(KERNEL_OUT) \
		$(if $(ARM_CROSS_COMPILE),$(ARM_CROSS_COMPILE),$(KERNEL_CROSS_COMPILE))
	mv $(I2SMIC_FOLDER)/snd-i2s_mic.ko $(KERNEL_MODULES_OUT)
	$(if $(ARM_EABI_TOOLCHAIN),$(ARM_EABI_TOOLCHAIN)/arm-eabi-strip, \
		$(KERNEL_TOOLCHAIN_PATH)strip) --strip-unneeded $(KERNEL_MODULES_OUT)/snd-i2s_mic.ko

TARGET_KERNEL_MODULES += I2SMIC_MODULE
